// <auto-generated />
using System;
using GardenBlog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GardenBlog.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class BlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GardenBlog.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new { CategoryId = 1, CategoryName = "Indoor" },
                        new { CategoryId = 2, CategoryName = "Outdoor" }
                    );
                });

            modelBuilder.Entity("GardenBlog.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("Body");

                    b.Property<int>("CategoryId");

                    b.Property<int?>("TagId");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<string>("Title");

                    b.HasKey("PostId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TagId");

                    b.ToTable("Posts");

                    b.HasData(
                        new { PostId = 1, Author = "Blair", Body = "I've found that the spider plant is the most effective at cleaning the air in my home. As someone with asthma, I can attest that this plant has done wonders for my breathing!", CategoryId = 1, TimeStamp = new DateTime(2019, 7, 1, 3, 0, 48, 382, DateTimeKind.Local), Title = "Spider Plant" },
                        new { PostId = 2, Author = "Bridget", Body = "I know this plant is easy to care for inside, but does anyone else have an issue with the ivy climbing on every other plant within a 5 mile radius? Asking for a friend...", CategoryId = 1, TimeStamp = new DateTime(2019, 7, 1, 3, 0, 48, 383, DateTimeKind.Local), Title = "English Ivy" },
                        new { PostId = 3, Author = "Kyle", Body = "I just planted a burning bush off my back porch and the leaves all fell off within the week. Is it dead or just didn't take the transplant well?", CategoryId = 1, TimeStamp = new DateTime(2019, 7, 1, 3, 0, 48, 383, DateTimeKind.Local), Title = "Burning Bush" },
                        new { PostId = 4, Author = "Elise", Body = "Last year I planted 4 asiatic lily plants and after my dog dug them up on multiple occassions, I just assumed they were dead. But this year, I have 9 plants growing! I'm so excited!", CategoryId = 2, TimeStamp = new DateTime(2019, 7, 1, 3, 0, 48, 383, DateTimeKind.Local), Title = "Asiatic Lilies" },
                        new { PostId = 5, Author = "Peter", Body = "I have a little bird bath fountain that I just put lily pads in. Now I have a couple peepers and the birds seem to not be using it anymore. Do you think the frogs scared them away? Or are birds scared of lily pads and I just didn't know about it?", CategoryId = 2, TimeStamp = new DateTime(2019, 7, 1, 3, 0, 48, 383, DateTimeKind.Local), Title = "Lily Pads" },
                        new { PostId = 6, Author = "Miranda", Body = "I just came across this entire acre field that plants sunflowers every year outside of Avon. It's so gorgeous, you have to check it out! It's so bright and yellow, and such a fun walk thorugh the field, it's a must do in the 2 weeks they're in full bloom!", CategoryId = 1, TimeStamp = new DateTime(2019, 7, 1, 3, 0, 48, 383, DateTimeKind.Local), Title = "Sunflowers" },
                        new { PostId = 7, Author = "Travis", Body = "Black mulch beware!! I've found that the black mulch actually has overheated my softer plants. Just make sure to keep a good eye out on your plants after laying mulch. The black mulch tends to fade rather quickly, so the first 2 weeks are key.", CategoryId = 2, TimeStamp = new DateTime(2019, 7, 1, 3, 0, 48, 383, DateTimeKind.Local), Title = "Mulch" }
                    );
                });

            modelBuilder.Entity("GardenBlog.Models.PostTag", b =>
                {
                    b.Property<int>("PostId");

                    b.Property<int>("TagId");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTags");

                    b.HasData(
                        new { PostId = 1, TagId = 2 },
                        new { PostId = 2, TagId = 1 },
                        new { PostId = 3, TagId = 2 }
                    );
                });

            modelBuilder.Entity("GardenBlog.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TagName");

                    b.HasKey("TagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new { TagId = 1, TagName = "mulch" },
                        new { TagId = 2, TagName = "ivy" },
                        new { TagId = 3, TagName = "orange" },
                        new { TagId = 4, TagName = "colorful" },
                        new { TagId = 5, TagName = "high-maintenance" },
                        new { TagId = 6, TagName = "easy-watering" },
                        new { TagId = 7, TagName = "direct-sun" },
                        new { TagId = 8, TagName = "low-maintenance" }
                    );
                });

            modelBuilder.Entity("GardenBlog.Models.Post", b =>
                {
                    b.HasOne("GardenBlog.Models.Category", "Category")
                        .WithMany("PostList")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GardenBlog.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId");
                });

            modelBuilder.Entity("GardenBlog.Models.PostTag", b =>
                {
                    b.HasOne("GardenBlog.Models.Post", "Post")
                        .WithMany("PostTagList")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GardenBlog.Models.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
